variables:
    VAGRANT_DEFAULT_PROVIDER: virtualbox
before_script:
    - mkdir -p ../${PWD##*/}.vagrant
    - ln -s ../${PWD##*/}.vagrant .vagrant
    - export DESTROY_BOX=false
jobs:
    script: ./scripts/build_ci.sh
    tags:
        - shell
        - virtualbox
